# Generated by Django 5.0.2 on 2024-03-09 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Zusatzleistung')),
            ],
            options={
                'verbose_name_plural': 'Zusatzleistungen',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prename', models.CharField(blank=True, max_length=50, verbose_name='Vorname')),
                ('Surname', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Kontaktliste',
            },
        ),
        migrations.CreateModel(
            name='CostPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Leistungsposition')),
                ('Measure', models.CharField(choices=[('1', 'h'), ('2', 'm'), ('3', 'm²'), ('4', 'm³')], max_length=2, verbose_name='Einheit')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preis pro Einheit in €')),
            ],
            options={
                'verbose_name_plural': 'Leistungsverzeichnis',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Equipment')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Geoposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Örtlichkeit')),
            ],
            options={
                'verbose_name_plural': 'Örtlichkeiten',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Anlage')),
            ],
            options={
                'verbose_name_plural': 'Anlagen',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Ebene')),
            ],
            options={
                'verbose_name_plural': 'Ebenen',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Bereich')),
                ('Contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.contact', verbose_name='Ansprechpartner')),
            ],
            options={
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('ScaffoldID', models.AutoField(help_text='Die Gerüstnummer wird automatisch erzeugt.', primary_key=True, serialize=False)),
                ('Length', models.DecimalField(blank=True, decimal_places=2, help_text='Länge in m²', max_digits=7, null=True, verbose_name='Plan Länge')),
                ('Width', models.DecimalField(blank=True, decimal_places=2, help_text='Breite in m²', max_digits=7, null=True, verbose_name='Plan Breite')),
                ('Height', models.DecimalField(blank=True, decimal_places=2, help_text='Höhe in m²', max_digits=7, null=True, verbose_name='Plan Höhe')),
                ('Amount', models.DecimalField(blank=True, decimal_places=0, help_text='Anzahl der Gerüste', max_digits=4, null=True, verbose_name='Plan Anzahl')),
                ('Area', models.ForeignKey(blank=True, help_text='Bereich.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.area', verbose_name='Bereich')),
                ('Equipment', models.ForeignKey(blank=True, help_text='Equipment.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.equipment', verbose_name='Equipment')),
                ('Geoposition', models.ForeignKey(help_text='Örtlichkeit', on_delete=django.db.models.deletion.CASCADE, to='hello.geoposition', verbose_name='Örtlichkeit')),
                ('Installation', models.ForeignKey(blank=True, help_text='Anlage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.installation', verbose_name='Anlage')),
                ('Level', models.ForeignKey(blank=True, help_text='Level', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.level', verbose_name='Ebene')),
            ],
            options={
                'verbose_name_plural': 'Gerüste',
            },
        ),
        migrations.CreateModel(
            name='ScaffoldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Gerüstversion')),
                ('Type', models.CharField(blank=True, choices=[('1', 'Anmeldung'), ('2', 'Erweiterung')], max_length=12)),
                ('RegistrationDate', models.DateField(default=django.utils.timezone.now, verbose_name='Anmeldedatum')),
                ('SetupDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Aufbaudatum')),
                ('Logout', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Abmeldedatum')),
                ('AdditionalServices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.additionalservices')),
                ('Scaffold', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.scaffold', verbose_name='Geruest')),
            ],
            options={
                'verbose_name_plural': 'Gerüstpositionen',
            },
        ),
        migrations.CreateModel(
            name='ChosenCostPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetLength', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Länge')),
                ('TargetWidth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Breite')),
                ('TargetHeight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Höhe')),
                ('TargetAmount', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Plan Anzahl')),
                ('TargetHours', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Plan Stunden')),
                ('Length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Länge')),
                ('Width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Breite')),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Höhe')),
                ('Amount', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='IST Anzahl')),
                ('Hours', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='IST Stunden')),
                ('Requested', models.BooleanField(default=False, verbose_name='ist freigegeben')),
                ('Confirmed', models.BooleanField(default=False, verbose_name='ist bestätigt')),
                ('CostPosition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.costposition', verbose_name='Leistungsposition')),
                ('ScaffoldPosition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.scaffoldposition', verbose_name='Gerüstversion')),
            ],
            options={
                'verbose_name_plural': 'Leistungspositionen',
            },
        ),
    ]
