# Generated by Django 5.0.2 on 2024-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaffoldposition',
            name='AdditionalServices',
        ),
        migrations.AddField(
            model_name='scaffoldposition',
            name='AdditionalServices',
            field=models.ManyToManyField(to='hello.additionalservices'),
        ),
    ]
