# Generated by Django 5.0.2 on 2024-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(blank=True, max_length=50, verbose_name='Vorname')),
                ('Nachname', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
