# Generated by Django 5.0.2 on 2024-02-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Equipment')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Geoposition',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Oertlichkeit')),
            ],
            options={
                'verbose_name_plural': 'Oertlichkeiten',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Anlage')),
            ],
            options={
                'verbose_name_plural': 'Anlagen',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ebene')),
            ],
            options={
                'verbose_name_plural': 'Ebenen',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Kontaktliste'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Vorname',
            new_name='Prename',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Nachname',
            new_name='Surname',
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Bereich')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.contact', verbose_name='Ansprechpartner')),
            ],
            options={
                'verbose_name_plural': 'Bereiche',
            },
        ),
    ]
