# Generated by Django 5.0.2 on 2024-02-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_equipment_geoposition_installation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.contact', verbose_name='Ansprechpartner'),
        ),
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('ScaffoldID', models.AutoField(help_text='Die Gerüstnummer wird automatisch erzeugt.', primary_key=True, serialize=False)),
                ('Length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Länge')),
                ('Width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Breite')),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Höhe')),
                ('Amount', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Anzahl')),
                ('Area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.area', verbose_name='Bereich')),
                ('Equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.equipment', verbose_name='Equipment')),
                ('Geoposition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.geoposition', verbose_name='Oertlichkeit')),
                ('Installation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.installation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name_plural': 'Gerüste',
            },
        ),
    ]
