# Generated by Django 5.0.2 on 2024-02-25 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_alter_area_contact_scaffold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Zusatzleistung')),
            ],
            options={
                'verbose_name_plural': 'Zusatzleistungen',
            },
        ),
        migrations.CreateModel(
            name='CostPosition',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Leistungsposition')),
                ('Measure', models.CharField(max_length=50, verbose_name='Einheit')),
                ('Price', models.CharField(max_length=50, verbose_name='Preis pro Einheit')),
            ],
            options={
                'verbose_name_plural': 'Leistungsverzeichnis',
            },
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Plan Anzahl'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Höhe'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Länge'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Breite'),
        ),
        migrations.CreateModel(
            name='ScaffoldPosition',
            fields=[
                ('Version', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Gerüstversion')),
                ('Scaffold', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.scaffold', verbose_name='Geruest')),
            ],
            options={
                'verbose_name_plural': 'Gerüstpositionen',
            },
        ),
    ]
