# Generated by Django 5.0.2 on 2024-02-25 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_additionalservices_costposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaffoldposition',
            name='Logout',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Abmeldedatum'),
        ),
        migrations.AddField(
            model_name='scaffoldposition',
            name='RegistrationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Anmeldedatum'),
        ),
        migrations.AddField(
            model_name='scaffoldposition',
            name='SetupDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Aufbaudatum'),
        ),
        migrations.AddField(
            model_name='scaffoldposition',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', 'Anmeldung'), ('2', 'Erweiterung')], max_length=12),
        ),
        migrations.AddField(
            model_name='scaffoldposition',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scaffoldposition',
            name='Version',
            field=models.CharField(max_length=50, verbose_name='Gerüstversion'),
        ),
    ]
