# Generated by Django 5.0.2 on 2024-02-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_scaffoldposition_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaffoldposition',
            name='AdditionalServices',
            field=models.ManyToManyField(to='hello.additionalservices'),
        ),
        migrations.CreateModel(
            name='ChosenCostPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.area', verbose_name='Bereich')),
            ],
            options={
                'verbose_name_plural': 'Ebenen',
            },
        ),
    ]
