# Generated by Django 5.0.2 on 2024-02-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_scaffoldposition_additionalservices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosencostposition',
            options={'verbose_name_plural': 'Leistungspositionen'},
        ),
        migrations.RemoveField(
            model_name='chosencostposition',
            name='Area',
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='CostPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.costposition', verbose_name='Leistungsposition'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='ScaffoldPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.scaffoldposition', verbose_name='Gerüstversion'),
        ),
        migrations.AlterField(
            model_name='costposition',
            name='Measure',
            field=models.CharField(choices=[('1', 'h'), ('2', 'm'), ('3', 'm²'), ('4', 'm³')], max_length=2, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='costposition',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preis pro Einheit in €'),
        ),
        migrations.AlterField(
            model_name='scaffoldposition',
            name='Version',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Gerüstversion'),
        ),
    ]
