# Generated by Django 5.0.2 on 2024-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_alter_chosencostposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencostposition',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='IST Anzahl'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='Height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Höhe'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='Hours',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='IST Stunden'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='Length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Länge'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='TargetAmount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Plan Anzahl'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='TargetHeight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Höhe'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='TargetHours',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Plan Stunden'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='TargetLength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Länge'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='TargetWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Plan Breite'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='Width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IST Breite'),
        ),
    ]
