# Generated by Django 5.0.2 on 2024-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_chosencostposition_amount_chosencostposition_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencostposition',
            name='Confirmed',
            field=models.BooleanField(default=False, verbose_name='ist bestätigt'),
        ),
        migrations.AddField(
            model_name='chosencostposition',
            name='Requested',
            field=models.BooleanField(default=False, verbose_name='ist freigegeben'),
        ),
    ]
