# Generated by Django 5.0.2 on 2024-03-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_chosencostposition_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaffold',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.level', verbose_name='Ebene'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.area', verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Geoposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.geoposition', verbose_name='Oertlichkeit'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.installation', verbose_name='Anlage'),
        ),
    ]
