# Generated by Django 5.0.2 on 2024-03-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_scaffold_level_alter_scaffold_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoposition',
            options={'verbose_name_plural': 'Örtlichkeiten'},
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Örtlichkeit'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Anzahl der Gerüste', max_digits=4, null=True, verbose_name='Plan Anzahl'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Area',
            field=models.ForeignKey(blank=True, help_text='Bereich.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.area', verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Geoposition',
            field=models.ForeignKey(help_text='Örtlichkeit', on_delete=django.db.models.deletion.CASCADE, to='hello.geoposition', verbose_name='Oertlichkeit'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Höhe in m²', max_digits=7, null=True, verbose_name='Plan Höhe'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Installation',
            field=models.ForeignKey(blank=True, help_text='Anlage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.installation', verbose_name='Anlage'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Länge in m²', max_digits=7, null=True, verbose_name='Plan Länge'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Level',
            field=models.ForeignKey(blank=True, help_text='Level', null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.level', verbose_name='Ebene'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='Width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Breite in m²', max_digits=7, null=True, verbose_name='Plan Breite'),
        ),
    ]
